apiVersion: apps/v1
kind: Deployment
metadata:
  name: mem-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mem-app
  template:
    metadata:
      labels:
        app: mem-app
    spec:
      containers:
        - name: mem-container
          image: ghcr.io/yandex-practicum/scaletestapp
          resources:
            limits:
              memory: "30Mi"
