apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mem-app-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mem-app
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - targetPort: 8080
      path: /metrics
      interval: 15s
